services:
  postgres:
    image: postgres:15
    container_name: movies_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: movies123
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: